language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-28.0.2
    - android-27
    - extra-google-m2repository

script:
  - keytool -genkey -v -keystore /tmp/keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias key -storepass changeit -dname "CN=My Warwick, OU=IT Services, O=University of Warwick, L=Coventry, ST=West Midlands, C=GB" -keypass changeit
  - echo "MyWarwick.keystore=/tmp/keystore.jks" >> app/gradle.properties
  - echo "MyWarwick.keyAlias=key" >> app/gradle.properties
  - echo "MyWarwick.keyPass=changeit" >> app/gradle.properties
  - cp app/google-services.json.example app/google-services.json
  - ./gradlew test build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - yes | sdkmanager "platforms;android-27" 
  - yes | sdkmanager "build-tools;28.0.3"
