language: android

android:
  components:
    - build-tools-28.0.2
    - android-27
    - extra-google-m2repository

script:
  - echo "MyWarwick.keystore=/dev/null" >> app/gradle.properties
  - echo "MyWarwick.keyAlias=" >> app/gradle.properties
  - echo "MyWarwick.keyPass=" >> app/gradle.properties
  - cp app/google-services.json.example app/google-services.json
  - ./gradlew build connectedCheck

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - yes | sdkmanager --licenses
